### ISSUE TITLE
Impossible to do the update

### ISSUE THREAD

**Issue by Matthieu-mi** [pibooth/pibooth-qrcode#13]
Hello
I find your code excellent but I've a little problem
When I install de new version and I run the pibooth on raspberry, it's always the 0.0.3 version of pibooth Qr-code which be launch.
I reinstall many times the code but I don't find the solution.
Do you have an idea????
Thank you and sorry for my English

**Comment by anxuae** [comment]
Hi @Matthieu-mi 

Be sure to remove all previously installed version before, run the 2 commands below:

```
sudo pip3 uninstall pibooth-qrcode
pip3 uninstall pibooth-qrcode
```

then re-install:

```
pip3 install pibooth-qrcode
```

**Comment by anxuae** [comment]
Seems to be fixed, please re-open if necessary
