### ISSUE TITLE
Wait state and Google Photos link

### ISSUE THREAD

**Issue by kashuuu** [pibooth/pibooth-qrcode#14]
Hi,
First thanks a lot for pibooth and the various addons! This is great! I have two questions:
1. Is there a way to remove the QR code after x seconds when in 'wait' state (similar to what is done for the picture in pibooth)?
2. Is it possible to get this to work with Google Photos? I also use the Google photos addon and would like to display the URL to the picture uploaded, but from what I understand the actual picture name once uploaded is randomly generated by Google.

**Comment by anxuae** [comment]
1. fixed: QR Code will be hidden if the previous picture is hidden
2. No it is not possible for now. Googlge generate random URL.
