### ISSUE TITLE
Link Google Photo's

### ISSUE THREAD

**Issue by DennisD88** [pibooth/pibooth-qrcode#15]
How I know what this part of the link is;

https://photos.google.com/share/**AxFF4t56kiJiu89m**/2021-06-11-10-14-08_pibooth.jpg

The last part is the name of the image file.

**Comment by anxuae** [comment]
Plugin [google-photo](https://github.com/pibooth/pibooth-google-photo) is being updated in order to give access to the picture URL

**Comment by anxuae** [comment]
Install last version of plugins:
- https://github.com/pibooth/pibooth-google-photo v1.1.1
- https://github.com/pibooth/pibooth-qrcode v1.0.2

Then set the ``[QRCODE][prefix_url]`` = `{url}`
