### ISSUE TITLE
2 qrcode

### ISSUE THREAD

**Issue by chonchon033** [pibooth/pibooth-qrcode#16]
Hello
I wanted to know if we could display 2 qrcodes.
Thank you

**Comment by anxuae** [comment]
Hi,

No it is not possible. And is is very difficult to implement is in a generic way.
Only possibility is to clone this repository, then update the code of this plugin in order to fit to your needs.

**Comment by anxuae** [comment]
Can you describe exactly why do you need 2 QR codes?

**Comment by chonchon033** [comment]
Hello
I used the program from: https://trevilly.com/borne-photos-autonome-automatique-et-avec-galerie-web-integree-raspberry-pi/#11
To create a wifi access point and a gallery, but you need 2 QR codes to access it.
That's why.
Thank you

**Comment by werdeil** [comment]
Hello,

From what I understand the Wifi QR code is fixed and won't changed at each picture, then I guess the easier way to do it is to print the QR code, and stick it somewhere on the pibooth no?

**Comment by chonchon033** [comment]
Hello
Yes I can print them and put them on the photobooth, but it was just to know if it was possible.
thanks again

**Comment by anxuae** [comment]
You can effectively change the code of this plugin. But easiest remain to print the QR code for wifi access
