### ISSUE TITLE
Individual photo link just with google account

### ISSUE THREAD

**Issue by mhilcher** [pibooth/pibooth-qrcode#17]
>Install last version of plugins:
>- https://github.com/pibooth/pibooth-google-photo v1.1.1
>- https://github.com/pibooth/pibooth-qrcode v1.0.2
>
>Then set the ``[QRCODE][prefix_url]`` = `{url}`
>
>_Originally posted by @anxuae in https://github.com/pibooth/pibooth-qrcode/issues/15#issuecomment-1097171593_

Hi, I tried that but with the direct link you have to login to a google account before anything is shown.
Not everyone has a google account, do you know if there is another way to access a single photo without an account?

Thank you and best wishes,
Martin

**Comment by anxuae** [comment]
Hi @mhilcher ,

The only link given when picture is uploaded if the one that you get when flashing Qrcode. See `productUrl` in https://developers.google.com/photos/library/guides/access-media-items

Maybe this is a parameter of your Google Photo account that you have to setup?

**Comment by anxuae** [comment]
Looking deeper in Google Photo doc, maybe using the `baseUrl` could solve your issue:
But link is valid only for 60min...

<img width="800" alt="Capture d’écran 2022-04-20 à 20 41 01" src="https://user-images.githubusercontent.com/25277953/164300554-de44fc88-04fa-4d83-a659-ccd96244f9df.png">

**Comment by mhilcher** [comment]
> Looking deeper in Google Photo doc, maybe using the `baseUrl` could solve your issue: But link is valid only for 60min...
> 

Thx for your answer. 
Maybe I will have a look into this when my recent pibooth project is done, 60 minutes are more than enough. 
Meanwhile I use Dropbox, the sdk has a command files_get_temporary_link(path), which works with my dropbox share for everyone without authentication. 

Google Photos is still the more interesting service because Dropbox just offers 2 GB for a free account. 
But this is still good enough for 2500 to 3500 pibooth pictures if it is just used for pibooth.

**Comment by anxuae** [comment]
I've tested with baseUrl and it seems to be possible to access without authentication. However link is so big that generated QRCode size take more that 1/4 of the screen... so next problem

**Comment by mhilcher** [comment]
> I've tested with baseUrl and it seems to be possible to access without authentication. However link is so big that generated QRCode size take more that 1/4 of the screen... so next problem

That's the same with dropbox, it creates a real huge QR Code.
No problem for me at the moment as I am using a 19'' Display and piboot in fullscreen mode.
But sure a problem with small displays.

**Comment by anxuae** [comment]
@mhilcher `pibooth-google-photo` v1.2.1 will give you an URL without need of login into Google Photos

**Comment by Aurel-Charles** [comment]
Hi guys! I just tested it with  **the [QRCODE][prefix_url] = {url}**
but its big QR code for my 7" screen. 
Is there a way to scall it down so it doesn't look bad??

**Comment by anxuae** [comment]
The QR Code size depends on how many characters you have to encode.
The URL returned by plugin `pibooth-google-photo` or `pibooth-dropbox` is very long so the QR Code is huge.
Maybe we can reduce the size of the generated picture but scan may fail.
