### ISSUE TITLE
Google photo QRCode link not working

### ISSUE THREAD

**Issue by chevallierce** [pibooth/pibooth-qrcode#19]
First I would like to thanks for the great job you have done. I'm not a dev, I'm just a simple user and you made a very handfull plugin.

I have an issue, maybe because of my poor knowledge but I need some help.

I manage to upload my pibooth picture to a google photo album.
I made the configuration to the plugin via the google's credential.
If the prefix URL is : https://photos.app.goo.gl/XxXxXxXxXxXxXxXxXx , it works and I manage to go to the google album where all the pibooth pictures are dropped.
But if the prefix URL is : https://photos.app.goo.gl/XxXxXxXxXxXxXxXxXx/{picture} , I have an error page saying : "https://goog.gl/app/photos/XxXxXxXxXxXxXxXxXx/YYYY-MM-DD-HH-mm-ss_pibooth.jpg?_nr=1" is not a valid DynamicLink.

Is anybody manage to use google photo to have access to one picture (and only one, not the entire album) through the QRCode plugin?

As I said, I m not a dev so maybe the solution is obvious, and if it is I apologize in advance.

**Comment by MikkeBoomBoom** [comment]
Same issue as well, maybe Google changed how they name their images in Google Photo?

**Comment by rubkec** [comment]
any updates on this?

**Comment by anxuae** [comment]
Just put:

```
prefix_url = {url}
```

regards
