### ISSUE TITLE
erreur installation package

### ISSUE THREAD

**Issue by guigui91** [pibooth/pibooth-qrcode#2]
bonjour est ce que cela fonctionne ? j'ai une erreur a l'installation du package? merci a vous

**Comment by werdeil** [comment]
Comme indiqué ce plugin est en cours de développement, pour l’instant son fonctionnement n’est pas garanti. Pouvez-vous m’en dire plus sur l’erreur que vous avez?

**Comment by sravel** [comment]
J'ai fais ma version en attendant l'officiel, 
C'est possible de l'installer en clonnant le dépot

git clone https://github.com/sravel/pibooth-qrcode
cd pibooth-qrcode
sudo python3 -m pip install --editable .

elle peux également contenir des bugs

**Comment by werdeil** [comment]
I finally took time to make the first release on pypi, it shall now works.

Closing the issue
