### ISSUE TITLE
Problem with QR Code plugin

### ISSUE THREAD

**Issue by gliepins** [pibooth/pibooth-qrcode#4]
Guys, Hi everyone!
I cannot get around the qrcode plugin. 
I upgraded the pibooth to latest,
I installed the plugin sucessfuly,
now running the pibooth app it throws an error!
Please, help! @sravel @anxuae 

Here is the error below:

```
#pygame-menu 4.0.2
Traceback (most recent call last):
  File "/usr/local/bin/pibooth", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pibooth/booth.py", line 422, in main
    plugin_manager = create_plugin_manager()
  File "/usr/local/lib/python3.7/dist-packages/pibooth/plugins/__init__.py", line 19, in create_plugin_manager
    plugin_manager.load_setuptools_entrypoints(hookspecs.hookspec.project_name)
  File "/usr/local/lib/python3.7/dist-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pibooth_qrcode'
```

**Comment by anxuae** [comment]
Bug is coming from the `pibooth-qrcode` plugin, fixed in PR #3.
Need a new release

**Comment by werdeil** [comment]
I release a new version of the qr code plugin (version 0.0.3) with @anxuae fix. Tell us if it fixes your issue

**Comment by gliepins** [comment]
Alright, thanks! I will test it right away and let you know!

**Comment by gliepins** [comment]
So far look good! Install went well and application no longer throws the error! I have not tested the qrcode useability itself though.

**Comment by gliepins** [comment]
The plugin seems to be working. However, what URL should I put in: qr_code_prefix = "???" to retreive the photo?
I tried to put in google photos link to the album, but the qrcode keeps linking to github instead. I clearly don't understand here something. 
In  the configuration I have put in a link to my google shared album. But the code when hoovering over with camera, shows "Github" name, and still opens up the github link. 
See the photo attachment.
Please help! It is almost all done otherways.

![Screenshot 2021-04-26 at 18 31 36](https://user-images.githubusercontent.com/26112780/116109657-ae67cc80-a6bd-11eb-88ba-035dc30d87a3.png)

**Comment by anxuae** [comment]
Be carful, the key has change in the new version, have a look to https://github.com/pibooth/pibooth-qrcode#configuration

**Comment by gliepins** [comment]
Yes, now that you mentioned it! The key is different from previous version. But along with the other problem (the config messing up) the current 0.0.3 qr plugin does NOT handle the config file right. So it has to be done by hand. 
Thank you, I think I am beginning to understand the qr code principle.

**Comment by anxuae** [comment]
I close this issue as it seems fixed.
Please re-open it if not.
