### ISSUE TITLE
QR code messes up configuration

### ISSUE THREAD

**Issue by gliepins** [pibooth/pibooth-qrcode#6]
I am still trying to get the qrcode plugin working.
Found an error and replicated it twice. Here are some observations:

1) the plugin does NOT update the configuration file on the first run! 
2) But it works using some defaults set in a different config file at "/usr/local/lib/python3.7/dist-packages/pibooth_qrcode.py"
3) from the pibooth application I can enter "settings" and there the plugin config is present. However when I change a setting in there, and exit the settings menu, application crashes.
4) After that the configuration file "/home/pi/.config/pibooth/pibooth.cfg" gets messed up with unwanted parentheses and commas. 

I attach a log file and the  messed up config file (config file I renamed to txt extension). 

[pibooth.log](https://github.com/pibooth/pibooth-qrcode/files/6383636/pibooth.log)

[pibooth.txt](https://github.com/pibooth/pibooth-qrcode/files/6383641/pibooth.txt)

**Comment by anxuae** [comment]
This is an issue with the pygame-menu library. It will be fixed in the next pibooth release.
For the moment, pthe only solution is to install a oldest version of pygame-menu:

```
pip3 install pygame-menu==3.1.0
```

**Comment by anxuae** [comment]
Now fixed since `pibooth` v2.0.2 released
