### ISSUE TITLE
QR code disappear on print event

### ISSUE THREAD

**Issue by basand0r** [pibooth/pibooth-qrcode#7]
Hi there,

I have installed the below plugin which works fine individually:
https://github.com/pibooth/pibooth-qrcode

However I noticed that the QR code disappears from the final screen once you touch the print button. Not sure if this is an expected behavior of the plugin as I did not find it implemented, so I suspect a problem with the hooks when the screen needs to be refreshed. I also noticed that the counter of the remaining printing option also disappears or blinks for a few milliseconds. 

Do you have any idea about it?

Thanks for your feedback in advance.

**Comment by anxuae** [comment]
Hi @detrist ,

I move the issue in the `pibooth-qrcode` plugin because it concerns only the plugin.
Your right, the plugin does not handle the "print action, I will fix it in the next version.

**Comment by basand0r** [comment]
Many thanks @anxuae for your reply, I did not find the missing part. So if I am not mistaken, the problem is that one of the hook implementaion is missing from the plugin. If so, I can also implement it and test.

My only concern is that there is the built-in printing plugin which has also a counter in the same corner of the screen, and which can also disappear when the QR plugin installed once you touch the final image for printing. I will check next week if this is related to the QR plugin or not and come back to you.

BR, detrist

**Comment by anxuae** [comment]
I made a quick fix in PR #8, you can check if it is better

**Comment by basand0r** [comment]
I will check it early next week and confirm.

**Comment by Aurel-Charles** [comment]
Hi I notice that in that in the 4 pictures mode , when its back to the start with the animated picture, QR code is also missing ....
I don't know if its  the same kind of fix to do or if its something else.

**Comment by anxuae** [comment]
Yes, it is the same issue, so you can test the code of the PR #8 : it should fix it.

**Comment by Aurel-Charles** [comment]
sweat!! I'll test that soon!!

**Comment by Aurel-Charles** [comment]
Just tried and it perfect now..! Thanks a lot!

**Comment by basand0r** [comment]
Sorry for the delay.... but indeed the fix works fine for me too.

Many Thanks.
