### ISSUE TITLE
Enhancement with side text !!??!

### ISSUE THREAD

**Issue by Aurel-Charles** [pibooth/pibooth-qrcode#9]
I thought maybe it could be nice to add a little text on the side.

Like having just a option in the QR-code option in the Menu setting below the colors to edit the text (with one ore two line)
Plus an other option to turn on/off the text if we want or not text.
Here is screen shot that I mod to show what I've in mind

<img width="802" alt="Screen Shot 2021-06-07 at 2 09 19 PM" src="https://user-images.githubusercontent.com/35420604/121014564-69de4f00-c79a-11eb-9e29-6f4fc070073d.png">

OR

<img width="802" alt="Screen Shot 2021-06-07 at 2 09 19 PM" src="https://user-images.githubusercontent.com/35420604/121015744-9e063f80-c79b-11eb-9761-bbd4ae07f960.png">

Also I understand that it's possible to me because I don't use the arrows.
It is just an idea. But if you think this a good one, maybe it's worth the shot!

**Comment by anxuae** [comment]
Hi @Aurel-Charles , thanks for your feedback
Yes we can add it
